alter table public.poems
  add column if not exists explainer text;

update public.poems set explainer = 'Blake imagines Jerusalem not as a distant place but as a moral possibility: a fairer, more humane England. The poem’s stirring language has made it feel patriotic, but its urgency is also a challenge to transform the world around us.' where title = 'Jerusalem';
update public.poems set explainer = 'Shelley places a boastful ruler’s ruined statue in an empty desert. The contrast between the inscription and the surrounding sand is the poem’s central irony: power can look permanent in its own moment, yet time makes even empires small.' where title = 'Ozymandias';
update public.poems set explainer = 'Wordsworth describes a sudden encounter with daffodils, then shows how the memory of them continues to nourish him later. It is often read as a poem about nature’s restorative power and about the imagination keeping a moment alive.' where title = 'I Wandered Lonely as a Cloud';
update public.poems set explainer = 'Keats lingers over the richness of late autumn: ripeness, harvesting and golden light. Beneath that fullness is a gentle awareness of ending; the poem does not deny decline, but treats it as part of a complete season.' where title = 'To Autumn';
update public.poems set explainer = 'Whitman begins with the individual self, then immediately opens that self out into the shared life of the world. The poem is commonly read as a declaration of democratic connection: each person matters, and no person is entirely separate.' where title = 'Song of Myself I';
update public.poems set explainer = 'Lawrence’s sharply comic attack on the bourgeoisie uses exaggeration to expose what he sees as social timidity and spiritual complacency. Its insults are deliberately theatrical; the poem’s energy is part of its protest.' where title = 'How Beastly the Bourgeois Is';
update public.poems set explainer = 'Owen overturns the old idea that dying for one’s country is noble and sweet. Its visceral details make the reader confront what patriotic slogans leave out: trauma, terror and the lasting cost of war.' where title = 'Dulce et Decorum Est';
update public.poems set explainer = 'Kipling addresses an empire at the height of its confidence and asks it to remember its limits. The repeated plea, “Lest we forget,” makes the poem a warning against arrogance rather than a simple celebration of power.' where title = 'Recessional';
update public.poems set explainer = 'This poem stages a quiet conflict between natural innocence and the harsh systems that can betray children. Blake’s simple language makes the loss of trust feel all the more devastating.' where title = 'A Little Boy Lost';
update public.poems set explainer = 'Yeats gives his speaker an unsettling calm: he expects death, but finds no noble cause or personal hatred behind it. The poem questions the easy stories nations tell about sacrifice in wartime.' where title = 'An Irish Airman Foresees his Death';
update public.poems set explainer = 'Wordsworth turns an ordinary city morning into something almost sacred. The poem asks us to notice London before it becomes busy: stillness lets its familiar buildings look newly beautiful.' where title = 'Composed upon Westminster Bridge';
update public.poems set explainer = 'Shelley’s sonnet is a furious diagnosis of political and social decay. Its final turn toward a “glorious Phantom” is often read as a fragile but defiant hope that renewal can emerge from a damaged present.' where title = 'England in 1819';
update public.poems set explainer = 'Dickinson makes hope into a small bird that continues singing even through storms. The image is powerful because hope is not shown as certainty or triumph, but as something modest and persistent.' where title = 'Hope is the Thing with Feathers';
update public.poems set explainer = 'Whitman celebrates the individual work of ordinary people: each singer has a distinct voice, yet together they form a larger music. It is often read as an idealised vision of democratic labour and shared belonging.' where title = 'I Hear America Singing';
update public.poems set explainer = 'Hardy looks beyond the violence of war to a field being ploughed, where the rhythms of everyday life carry on. The poem suggests that human conflict is temporary against older, slower continuities.' where title = 'In Time of ''The Breaking of Nations''';
update public.poems set explainer = 'Hopkins’s dense sound and sprung rhythm try to make a wild landscape feel alive on the page. The poem’s delight in rough, untamed nature becomes an argument for protecting what is easily dismissed as useless or messy.' where title = 'Inversnaid';
update public.poems set explainer = 'Blake’s repeated “charter’d” details make London seem measured, owned and constrained. The poem sees private suffering everywhere: in workers, soldiers and families, all caught in systems that promise order but create misery.' where title = 'London';
update public.poems set explainer = 'Dickinson turns revolution into a seed pod: compact, quiet, and full of unrealised force. The comparison suggests that profound change can begin invisibly, before anyone knows what it will become.' where title = 'Revolution is the Pod';
update public.poems set explainer = 'Shakespeare lists the corruptions that make life exhausting, then reveals that love is the reason the speaker cannot simply leave it all behind. The sonnet holds social anger and personal devotion in uneasy balance.' where title = 'Sonnet LXVI';
update public.poems set explainer = 'Milton praises Cromwell’s military and political achievement, but the poem also presses him toward restraint and liberty. It is both tribute and advice: power should protect conscience, not replace it.' where title = 'Sonnet XVI: Cromwell, Our Chief of Men';
update public.poems set explainer = 'Shirley compresses a large thought into a short lyric: rank, beauty and military glory all end in death. Its calm, ceremonial tone makes the message less bleak than clarifying—human equality is unavoidable.' where title = 'The Glories of Our Blood and State';
update public.poems set explainer = 'Yeats imagines a simple island refuge where peace arrives gradually, through sound, light and repeated natural rhythms. It is often read as a poem of longing: inner quiet is desired because modern life feels too noisy.' where title = 'The Lake Isle of Innisfree';
update public.poems set explainer = 'Written in the aftermath of the First World War, Yeats pictures a world losing its centre. The poem’s frightening “rough beast” is deliberately uncertain, which is why it has become a lasting image for historical dread and upheaval.' where title = 'The Second Coming';
update public.poems set explainer = 'Wordsworth criticises a culture so focused on acquiring and consuming that it has lost contact with the natural world. His dramatic wish to be a pagan is not literal belief, but a plea for a more vivid spiritual relationship with nature.' where title = 'The World Is Too Much With Us';
update public.poems set explainer = 'Hamlet’s famous question is not simply “should I live or die?” It weighs the pain of action against the fear of what follows death, showing how thought itself can both deepen suffering and prevent rash decisions.' where title = 'To be or not to be';
update public.poems set explainer = 'Wordsworth addresses the imprisoned leader of the Haitian Revolution as a symbol of courage and endurance. The sonnet turns his personal suffering into a wider appeal for freedom and moral attention.' where title = 'To Toussaint L''Ouverture';
